services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pistia
      POSTGRES_PASSWORD: dev_local
      POSTGRES_DB: pistia_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
