"""add_activo_to_servicios

Revision ID: 4e1e00b485a6
Revises: 24bb7d8d514f
Create Date: 2026-06-12 16:46:25.004119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1e00b485a6'
down_revision: Union[str, None] = '24bb7d8d514f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicios', sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicios', 'activo')
    # ### end Alembic commands ###
