"""fase3_tienda_galeria

Revision ID: b43d572938c8
Revises: c3d4e5f6a1b2
Create Date: 2026-06-30 03:12:15.326619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43d572938c8'
down_revision: Union[str, None] = 'c3d4e5f6a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galeria_fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('public_id', sa.String(length=200), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=2000), nullable=False),
    sa.Column('precio', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagenes_prenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prenda_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('public_id', sa.String(length=200), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prenda_id'], ['prendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas_prenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('prenda_id', sa.Integer(), nullable=False),
    sa.Column('talla', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'atendida', 'cancelada', name='estadoreservaprenda', native_enum=False, length=15), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['prenda_id'], ['prendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tallas_prenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prenda_id', sa.Integer(), nullable=False),
    sa.Column('talla', sa.String(length=20), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['prenda_id'], ['prendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prenda_id', 'talla', name='uq_talla_prenda')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tallas_prenda')
    op.drop_table('reservas_prenda')
    op.drop_table('imagenes_prenda')
    op.drop_table('prendas')
    op.drop_table('galeria_fotos')
    # ### end Alembic commands ###
